services:
  # ASP.NET Core Web API
  api:
    build:
      context: ./API/ToDoListAPI
      dockerfile: Dockerfile
    container_name: todolist-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      # ASP.NET Core Configuration
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      
      # Azure AD Configuration (from .env file or user secrets)
      - AzureAd__Instance=${AZURE_AD_INSTANCE}
      - AzureAd__TenantId=${AZURE_AD_TENANT_ID}
      - AzureAd__ClientId=${AZURE_AD_CLIENT_ID}
      - AzureAd__ClientSecret=${AZURE_AD_CLIENT_SECRET}
      
      # Swagger Configuration
      - Swagger__ClientId=${SWAGGER_CLIENT_ID}
      - Swagger__Scopes__ToDoList__Read=${SWAGGER_SCOPE_TODOLIST_READ}
      - Swagger__Scopes__ToDoList__ReadWrite=${SWAGGER_SCOPE_TODOLIST_READWRITE}
      - Swagger__Scopes__User__Read=${SWAGGER_SCOPE_USER_READ}
      
      # Override ports for Docker (use Docker mapped ports instead of local dev ports)
      - https_port=5001
      - http_port=5000
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React SPA
  spa:
    build:
      context: ./SPA
      dockerfile: Dockerfile
      args:
        - REACT_APP_TENANT_ID=${REACT_APP_TENANT_ID}
        - REACT_APP_TENANT_SUBDOMAIN=${REACT_APP_TENANT_SUBDOMAIN}
        - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
        - REACT_APP_API_CLIENT_ID=${REACT_APP_API_CLIENT_ID}
        - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT:-http://localhost:5000/api/todolist}
        - REACT_APP_REDIRECT_URI=${REACT_APP_REDIRECT_URI:-http://localhost:3000}
    container_name: todolist-spa
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      api:
        condition: service_healthy
    networks:
      - todolist-network

  # Console Daemon App
  console:
    build:
      context: ./Console
      dockerfile: Dockerfile
    container_name: todolist-console
    environment:
      # .NET Environment
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT:-Development}
      
      # Azure AD Configuration (from .env file)
      - AzureAd__Instance=${AZURE_AD_INSTANCE}
      - AzureAd__TenantId=${CONSOLE_AZURE_AD_TENANT_ID}
      - AzureAd__ClientId=${CONSOLE_AZURE_AD_CLIENT_ID}
      - AzureAd__ClientSecret=${CONSOLE_AZURE_AD_CLIENT_SECRET}
      
      # ToDoList API Configuration
      - ToDoListApi__BaseUrl=${TODOLIST_API_BASE_URL:-http://api:8080/api}
      - ToDoListApi__Scopes__0=${TODOLIST_API_SCOPE}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - todolist-network
    restart: unless-stopped

networks:
  todolist-network:
    driver: bridge
